### PR TITLE
Streamer: add this into the default enabled pacakge list

### PR DESCRIPTION
**Pull request by HaseenaSainul**

### CODE REVIEW

**Comment by wouterlucas** [comment]
will this also work on IMX and other exotic platforms?

**Comment by HaseenaSainul** [comment]
It will work either on the platform which support aamp by default or if add meta-wpe-restrcited layer into the build

**Comment by scthunderbolt** [comment]
Build error:

**Comment by HaseenaSainul** [comment]
Thanks Simon, I found the same issue while building with RDK images and found force fully settings streamer from the meta-comforts-raspberry pi layer, so waiting for the updates from RDK team

**Comment by scthunderbolt** [comment]
No problems, if you know a fix in other layers, please send it to me and I can take a look.

**Comment by HaseenaSainul** [comment]
Thank you, but you need some input from the team who requested me to enable streamer. So I will update you once I get input from them :)

**Comment by wouterlucas** [comment]
FYI with the change below:
```
diff --git a/recipes-wpe/wpeframework/include/streamer.inc b/recipes-wpe/wpeframework/include/streamer.inc
index afb5094..2a5925d 100644
--- a/recipes-wpe/wpeframework/include/streamer.inc
+++ b/recipes-wpe/wpeframework/include/streamer.inc
@@ -1,6 +1,6 @@
 # Streamer supports QAM or AAMP implementation
 # Add 'QAM' and/or 'Aamp' to STREAMER_IMPLEMENTATIONS
-STREAMER_IMPLEMENTATIONS ?= "Aamp"
+STREAMER_IMPLEMENTATIONS ?= "None"

 # AAMP variables
 AAMP_STREAMER_FRONTENDS        ?= "0"
```

The build continues fine for me without any issues. Can we move this PR along or just apply that? Because right now all RPI builds are broken...

**Comment by HaseenaSainul** [comment]
I think better is to merge this PR, @scrhunderbolt, could you please remove streamer pkgconfig setting from wpeframework plugins BB append file in meta-cmf-raspberrypi layer?

**Comment by scthunderbolt** [comment]
Please fix the conflicts and then I can test a change in meta-cmf-raspberrypi.

**Comment by HaseenaSainul** [comment]
@scthunderbolt, that conflicts is happening since the streamer is enabling from meta-cmf-raspberrypi layer as well. If I disable in my local build the build is success

**Comment by scthunderbolt** [comment]
No, I mean the merge conflicts. See below:
"
This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.
Conflicting files
recipes-wpe/wpeframework/wpeframework-plugins_git.bb
"
This has to be resolved first before I can try my change.

**Comment by scthunderbolt** [comment]
see:
||
V

**Comment by HaseenaSainul** [comment]
@scthunderbolt, Yea I resolved conflicts :)

**Comment by scthunderbolt** [comment]
Build is OK now with
 https://code.rdkcentral.com/r/c/components/generic/rdk-oe/meta-cmf-raspberrypi/+/35904

**Comment by wouterlucas** [comment]
You've just added
```
PACKAGECONFIG_remove = "streamer"
```

Sounds counter intuitive to remove something that we've added here just to make a build compile.

If its not wanted, lets just not enable it in the default @Haseenamol ?

**Comment by HaseenaSainul** [comment]
@scthunderbolt, please do not add PACKAGECONFIG_remove = "streamer", instead remove it from the below line. Otherwise it will not allow me to add it from the wpe layer as well
PACKAGECONFIG_append_thunder = " \
  ${@bb.utils.contains('DISTRO_FEATURES', 'systemd','systemdconnector', '', d)} \
  **streamer** systemcommands DHCPServer securityagent ioconnector firmwarecontrol\
  "

**Comment by scthunderbolt** [comment]
Please see https://code.rdkcentral.com/r/c/components/generic/rdk-oe/meta-cmf-raspberrypi/+/35965 as an alternative.

**Comment by HaseenaSainul** [comment]
Yes, thats what I suggested, thank you @scthunderbolt

**Pull request merged**
