### PR TITLE
[westeros] : Moved to 1.01.19 version to solve the westeros graphics …

### PR DESCRIPTION
**Pull request by manikandankrishnasamy**
Faced the westeros graphics freeze issue once we launched the westeros application after 2 to 3 sec got freezed.

westeros graphics freeze issue is caused due to EGLAPI EGLBoolean eglSwapBuffers( EGLDisplay dpy, EGLSurface surface ) pthread_mutex_lock & pthread_mutex_unlock handling changes on may 14th commit. 

Issue causing update is reverted to original code and committed on the latest version of westeros [1.01.19]

So we moved the meta-wpe to the 1.01.19 version.

Signed-off-by: manikandan.k <manikandan.k@ltts.com>

### CODE REVIEW

**Comment by petegriffin** [comment]
@manikandankrishnasamy Thanks for sending the pull request. In the commit message can you mention the short SRCREV of the commit in Westeros that caused the regression, and also short SRCREV of the commit that reverted it? You can get that using 'git rev-parse --short' command

Something like

Westeros graphics freeze issue is caused due to EGLAPI EGLBoolean eglSwapBuffers( EGLDisplay dpy, EGLSurface surface ) pthread_mutex_lock & pthread_mutex_unlock handling changes which was introduced in 020d818, and later reverted in 040d612 which is part of westeros [1.01.19] release.

Also can you use update the patch to use Linaro SoB / email address for Linaro work?

**Comment by manikandankrishnasamy** [comment]
@petegriffin Thanks for your comments. I have updated the commit message as per your request  and pushed the changes.

**Comment by petegriffin** [comment]
@manikandankrishnasamy Thanks for the update :) Only problem is this pull request now contains 3 commits.

Can you 'git rebase' and squash into just 1 clean commit, and then git push -f to update this pull request (then we have nice clean git history)? 

Whilst you're there, subject line would be better as "[westeros] : Moved to 1.01.19 version to solve graphics issue" then blank line, then the explanation like you currently have.

**Comment by manikandankrishnasamy** [comment]
@petegriffin  Now i have re-based and updated with single commit id. Also changed the subject line as per your suggestion. Please review it.

**Comment by manikandankrishnasamy** [comment]
@woutermeek Can you please review and merge this approved pull request..

**Pull request merged**
