### PR TITLE
gstreamer: use wildcard instead of fixed version number in bbappends

### PR DESCRIPTION
**Pull request by hhromic**
Hi guys,
Recently gstreamer got a bugfix release in upstream (1.14.0 -> 1.14.1) and the bbappends in this layer broke because they are tied to very specific minor versions (in this case, 1.14.0).
To make life easier, this PR makes bbappends not specific to minor versions, i.e. 1.14.x, so it doesn't break on upstream minor upgrades.

### CODE REVIEW

**Comment by wouterlucas** [comment]
Done, though it might break if we certain patches go upstream that we carry already. Having strict v.s. a little looser are the same "risk" from time to time. I do agree in this case going from 1.14.0 -> 1.14.1 is OK and having a 1.14.% is fine for now.

**Comment by hhromic** [comment]
I understand minor versions in gstreamer are safe for unsupervised upgrades.
Of course, attention should be kept for patches that are merged upstream.
Fortunately for these cases anyway BitBake warns during do_patch() and the recipe can be further cleaned.

I have a curiosity question: I noticed that the bbappends are split into "global" and "version-specific". For example there is a `gstreamer1.0-plugins-base_%.bbappend` and a `gstreamer1.0-plugins-base_1.14.%.bbappend`.
Before, Yocto used to have two versions of gstreamer (0.x and 1.x series) and hence the split bbappends approach made sense (you only want to patch 1.x versions). However since a while Poky is only providing 1.x series now:
```
commit f8232d79aff4fa419c2a0e7ccae38615c9c1157a
Author: Alexander Kanavin <alex.kanavin@gmail.com>
Date:   Mon May 18 16:58:40 2015 +0300

    gstreamer: remove 0.10 recipes

    gstreamer 0.10 is still available from meta-openembedded/meta-multimedia

    See also
    https://bugzilla.yoctoproject.org/show_bug.cgi?id=6294
    http://lists.openembedded.org/pipermail/openembedded-core/2015-April/104276.html
```

Wouldn't it make more sense now to just have one bbappend per component?  So we have less files to keep track of and simplify?

**Comment by hhromic** [comment]
Moreover, 1.x recipes are named `gstreamer1.0-*` and so there is no confusion or mismatch with the bbappends whatsover.

**Comment by wouterlucas** [comment]
This is a remnant of dealing with multiple version of Gstreamer all in 1 branch. In the early beginnings of meta-wpe (when it was still meta-metrological) we had 1 branch that dealt with Gstreamer 1.4.x, 1.6.x and 1.8.x. At the time there where some switches that where common across all versions and they where placed in gstreamer1.0-plugins-<X>_%.bbappend while some version specific ones had their actual version number assigned to it. This was  a time where we supported multiple versions of Gstreamer in 1 branch all collapsed into 1 layer. 

After that it got rather confusing and I've started splitting our layer per the same versions as Yocto and this is no longer strictly required. Though to me it still makes sense as "major switches" version "version specific patches" and I've never bothered with it :)

**Pull request merged**
