### PR TITLE
wpewebkit: patch for holepunch buffer

### PR DESCRIPTION
**Pull request by Khan3033**
Signed-off-by: rkhan467 <Riyaz.l@ltts.com>

### CODE REVIEW

**Comment by Khan3033** [comment]
Hi @kraj please review this change and merge, thanks

**Comment by Khan3033** [comment]
Hi @kraj expecting to merge this change.

**Comment by wouterlucas** [comment]
Is there a reason for a separate patch v.s a bump of wpe 2.22? If there's no specific reason for it I'd prefer we just bump wpewebkit to the latest revision of 2.22 which includes this patch.

**Comment by Khan3033** [comment]
> Any update on the patch vs bump?

Hi @wouterlucas we have bumped wpewebkit to the latest revision of 2.22 which includes this patch.
please find below req id
https://github.com/WebPlatformForEmbedded/meta-wpe/pull/383

thanks riyaz.

**Comment by wouterlucas** [comment]
Ty - I'll close this

**Pull request closed without merging**
