### PR TITLE
cppsdk: Switch to using WPEFramework source location

### PR DESCRIPTION
**Pull request by kraj**
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by wuhanck** [comment]
@kraj 
Where is "git://git@github.com/WebPlatformForEmbedded/WPEFramework"?
I want to explore WPE, but I find that it is hard to get info.
Every README is broken.
Do I need become some special member-ship?

**Comment by kraj** [comment]
@wuhanck this is a repository which will be opensourced soon so yes its currently limited accessible, however for wpe to work you dont have to worry about it.  Remove

`
    cppsdk \                                                                   
    webbridge \                                                                
`

from recipes-core/packagegroups/packagegroup-rpi-ml-wpe.bb

and you should be good to go

**Comment by wuhanck** [comment]
@kraj 
Thank you very much!
I will try it.

**Comment by kraj** [comment]
rebased after fixing build with musl

**Comment by kraj** [comment]
@wouterlucas This patchset it tested both on glibc and musl ( now works ) please review and merge

**Comment by wouterlucas** [comment]
Lets do the rename of webbridge/cppsdk --> WPEFramework separately. This was already being worked on by Sander on another branch. That will also change the names and structure of the recipes in general. If you remove those commits I'd be happy to merge.

**Comment by kraj** [comment]
OK done

**Pull request merged**
