### PR TITLE
wpeframework patches to resolve build issues

### PR DESCRIPTION
**Pull request by moorthy-bs**

### CODE REVIEW

**Comment by HaseenaSainul** [comment]
@wouterlucas, These changes are already available with the Thunder master branches. Why we are making it as patch, instead moving to the latest ?

**Comment by wouterlucas** [comment]
Oh in that case I'd suggest to just bump to latest?

**Comment by moorthy-bs** [comment]
Yes, no need for these patches if all are bumped to the latest. But a long time there is no revision change in Thunder & nanoservices recipes is the reason upstreamed patches for that

**Comment by moorthy-bs** [comment]
bumping version [pull request](https://github.com/WebPlatformForEmbedded/meta-wpe/pull/441) is given

**Pull request closed without merging**
