### PR TITLE
fix logging with proper flag

### PR DESCRIPTION
**Pull request by psivasubramanian**
Depends on https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/507

### CODE REVIEW

**Comment by wouterlucas** [comment]
Please prefix commits with the components you're changing, in this case wpewebkit:
"wpewebkit: fix logging with proper flag"

**Comment by psivasubramanian** [comment]
Done.

**Comment by kraj** [comment]
@psivasubramanian please address @wouterlucas 's statement

**Comment by psivasubramanian** [comment]
> @psivasubramanian please address @wouterlucas 's statement

Hi @kraj, I amended the commit https://github.com/WebPlatformForEmbedded/meta-wpe/pull/228/commits/3dfc42d454c12f1f392db2818544a90b90cc8962 with @wouterlucas 's review comment. Is there anything I'm missing?

**Comment by kraj** [comment]
@wouterlucas can you take care of merging this one ?

**Comment by wouterlucas** [comment]
Done and merged in WPEWebKit as well, needs a bump though to line up.

**Pull request merged**
