### PR TITLE
wpeframework: Python2 to Python3 conversion of CppParser.py,JsonGener…

### PR DESCRIPTION
**Pull request by balav08**
…ator.py and StubGenerator.py

Signed-off-by: balav08 <balaji.velmurugan@ltts.com>

### CODE REVIEW

**Comment by bramoosterhuis** [comment]
It’s already there 
https://github.com/WebPlatformForEmbedded/Thunder/pull/289

**Comment by wouterlucas** [comment]
Ah, then why backport just 1 change instead of doing a bump?

**Comment by bramoosterhuis** [comment]
Ow wait I’m mess up commits now

**Comment by bramoosterhuis** [comment]
Tagging @sebaszm as he is father of the generators.

**Comment by bramoosterhuis** [comment]
@wouterlucas I just spoke to @sebaszm and we will put the upgrade to python3 on the backlog since it has some impact on the buildroot makefiles. Maybe accept the patches for now since the master of meta-wpe is the only place where python2 is obsolete for now.

**Comment by kraj** [comment]
> @wouterlucas I just spoke to @sebaszm and we will put the upgrade to python3 on the backlog since it has some impact on the buildroot makefiles. Maybe accept the patches for now since the master of meta-wpe is the only place where python2 is obsolete for now.

you can not put it on back burner since master is going tot be yocto 3.1 whch has removed py2 support and RDK is moving to this starting in this quarter, infact work has already begun.
I would prefer them to apply to meta-wpe if you need time to sort things out for upstream thunder thats fine. It will give you some breathing space while porting team is able to move forward.

**Comment by wouterlucas** [comment]
@kraj that is awesome news! I can't wait to ditch Morty and never look back. 
We'll align to see if we can move that upstream before that. Sounds good.

**Pull request merged**
