### PR TITLE
Drop harfbuzz 1.0.1 as it breaks morty

### PR DESCRIPTION
**Pull request by psivasubramanian**

### CODE REVIEW

**Comment by wouterlucas** [comment]
Seems to be okay for me, what breaks with harfbuzz 1.0.1?

**Comment by psivasubramanian** [comment]
@wouterlucas : WPE configure fails on harfbuzz-icu dependency which is missing due to incorrect flags. So, the PR  https://github.com/WebPlatformForEmbedded/meta-wpe/pull/173 is the actual fix. But since it was rejected & this recipe was dropped from master, I'm proposing the same to Morty.

**Comment by kraj** [comment]
@wouterlucas please apply https://github.com/WebPlatformForEmbedded/meta-wpe/pull/173 to morty I think thats best solution here.

@shiva can you post https://github.com/WebPlatformForEmbedded/meta-wpe/pull/173 for morty ?

**Comment by psivasubramanian** [comment]
@kraj Yes, please find https://github.com/WebPlatformForEmbedded/meta-wpe/pull/178 for morty.

**Comment by kraj** [comment]
@wouterlucas this can be closed

**Pull request closed without merging**
