### PR TITLE
meta-wpe: normalize GitHub SRC_URI in recipes for default protocol/branch

### PR DESCRIPTION
**Pull request by hhromic**
Normalize the GitHub SRC_URI of the recipes:

    gstreamer1.0-openwebrtc wpebackend-mesa wpebackend-rdk
    wpebackend wpeframework-plugins wpeframework-ui wpeframework wpewebkit

for accessing GitHub URIs using standard git protocol. Fixes the following warning:

    WARNING: wpeframework-ui-3.0+gitrAUTOINC+c0b3857405-r0 do_fetch:
    Failed to fetch URL git://git@github.com/WebPlatformForEmbedded/WPEFrameworkUI.git;protocol=ssh;branch=master,
    attempting MIRRORS if available

because of the fetcher trying to use SSH protocol without credentials. We can't assume
everyone has SSH keys configured, so just use the standard git protocol (the default).
Also, there is no need to specify the master branch as this is also a default in the fetcher.

### CODE REVIEW

**Comment by wouterlucas** [comment]
Looks good to me, though we can drop the openwebrtc entirely. That's a dead end and is not being used in wpewebkit anymore.

**Comment by hhromic** [comment]
Great. I changed the PR now to leave the openwebrtc openwebrtc alone so we can drop it in another PR.
I noticed that openwebrtc is mentioned in `recipes-wpe/wpewebkit/wpewebkit_2.20.bb`:

    PACKAGECONFIG[mediastream] = "-DENABLE_MEDIA_STREAM=ON,-DENABLE_MEDIA_STREAM=OFF,openwebrtc"

I'm not sure how to drop the openwebrtc recipe without affecting the build. Should I just remove that line? won't the mediastream package config break? Let me know how to properly clean it and I will make another PR.

**Comment by hhromic** [comment]
Updated the commit log, ready to merge.

**Comment by hhromic** [comment]
@wouterlucas : looks like removing the packageconfig line along with the recipe did no harm to the overall build. Can you confirm me this is the right way to remove openwebrtc so I prepare a PR?

**Comment by wouterlucas** [comment]
Yes, that package config line can be removed for now. Needs to be revised, this should depend on libwebrtc in the future. However I'm okay with leaving it out for now as the current downstream WPEWebKit does not work (yet) with WebRTC.

**Comment by hhromic** [comment]
Great, I will merge this PR now and prepare another for dropping the openwebrtc recipe.

By the way, please note that according to the Ericsson repository of the recipe, WebRTC is now supported by gstreamer 1.14: https://gstreamer.freedesktop.org/releases/1.14/
Given that gstreamer 1.14 is already available and used, perhaps is the way to go in future for WebRTC.

**Comment by wouterlucas** [comment]
Its not so much about what the webrtc library supports. It’s about what webkit supports in term of webrtc integration. 

And upstream a lot of effort has gone into supporting libwebrtc over owr. 

Ps the Gstreamer 1.14.x will get some love too. Hopefully we can start pushing patches soon. 

Thanks for the PR!

**Pull request merged**
