### PR TITLE
Aamp: patches to support glimagesink set reactangle, mpd file duration and…

### PR DESCRIPTION
**Pull request by HaseenaSainul**
… aamp ocdm patch name changes

### CODE REVIEW

**Comment by pavannandyala** [comment]
LGTM +1

**Comment by pavannandyala** [comment]
Patches related to aamp core for streamer nano service support

**Comment by wouterlucas** [comment]
@kraj they where part of https://github.com/WebPlatformForEmbedded/meta-wpe/pull/339

This was a PR to correct the missing import of previously added patches.

**Comment by kraj** [comment]
Ah I see

**Pull request merged**
